### ISSUE TITLE
Evolution 2# - OAuth for GitHub

### ISSUE THREAD

**Issue by app-generator** [app-generator/api-server-nodejs#16]
Hello @FullStackkDev! 

The API should be enhanced to support OAuth via Github.

> Requirements:

- the backward compatibility assured:
  - JWT Login 
  - existing API signature
- The library used in NodeJS should be actively supported and `alive` 
  - Please propose a few options here 

Ty!

**Comment by app-generator** [comment]
Hello @FullStackkDev 

Please provide more information about the implementation (super slim) and also a short `step-by-step` documentation
how a new user can use this feature. 

The information should provide:

- `env` variables (if needed)
- the OAuth callback URL
- the steps that the user should follow to configure GitHub 

The above documentation should provide only the super minimal information. 

Ty!

**Comment by FullStackkDev** [comment]
@app-generator Here is the documentation file for GitHub OAuth
